### ISSUE TITLE
[HELP] Upgrade pillow to version 7.1.0 or later

### ISSUE THREAD

**Issue by zakokor** [zakokor/pegao#5]
- Upgrade pillow to version 7.1.0 or later

**Comment by Pepper-Wood** [comment]
Hello! I took a look at this issue, and I'm not sure if Pillow is actually used by any of the code present. I didn't see any imports that used `Pillow` or `PIL`; I'm also not sure of what sort of dependency tree exists - if i.e. Django does require it under the hood.

The full list of breaking changes that would have to be amended are found here: https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#backwards-incompatible-changes But again, these don't exist in the codebase.

How are you spinning up the site locally? I guess my best bet would be to update the line in `requirements.txt`:
```
Pillow==7.2.0
```
and see what breaks.

**Comment by zakokor** [comment]
Hi! thank you for comment. I think it's requiered  for use ImageField.

**Comment by Pepper-Wood** [comment]
Oh nice! Thanks! Confirming that `ImageField` is a part of Pillow: https://www.geeksforgeeks.org/imagefield-django-models/
I double checked if there were other classes/variables/attributes with "Image" in the name like `ImageField` and couldn't find any others. `ImageField` or "field" are not found in the incompatible changes doc, so it sounds like it's still safe to upgrade as-is without requiring any code change. I'll file a quick PR.
